name: Lighthouse Audit Compare PR vs Main

on:
  pull_request:
    branches:
      - '**'

jobs:
  lighthouse-compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build PR branch
        env:
          WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
          NEXT_PUBLIC_WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
        run: npm run build

      - name: Start PR branch on port 3001
        env:
          WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
          NEXT_PUBLIC_WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
        run: |
          nohup npm run start -- -p 3001 > pr.log 2>&1 &
          sleep 20

      - name: Checkout main branch to separate folder
        run: |
          git fetch origin main
          git worktree add main-branch origin/main

      - name: Install & build main branch
        working-directory: ./main-branch
        run: |
          npm install
          WORDPRESS_API_URL="https://wp.keploy.io/graphql" NEXT_PUBLIC_WORDPRESS_API_URL="https://wp.keploy.io/graphql" npm run build

      - name: Start main branch on port 3000
        working-directory: ./main-branch
        env:
          WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
          NEXT_PUBLIC_WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
        run: |
          nohup npm run start -- -p 3000 > main.log 2>&1 &
          sleep 20
      
      - name: Debug Branch Info
        run: |
          echo "🔍 GitHub Context Branch Info"
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_SHA: ${{ github.sha }}"


      - name: Create output directory for Lighthouse
        run: mkdir -p ${{ github.workspace }}/tmp/artifacts

      - name: Run Lighthouse audit for both PR and Main
        uses: foo-software/lighthouse-check-action@master
        with:
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.head_ref }}
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: 'http://localhost:3000/blog,http://localhost:3001/blog'
          sha: ${{ github.sha }}


