name: Lighthouse Pull request Comparison

on: 
  pull_request: 
    branches: 
      - "**"

jobs:
  build-and-compare:
    name: Build both branches and compare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch (default)
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build PR branch
        env:
          WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
          NEXT_PUBLIC_WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
        run: npm run build

      - name: Start PR branch on port 3000
        env:
          WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
          NEXT_PUBLIC_WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
        run: |
          nohup npm run start -- -p 3000 > pr.log 2>&1 &
          sleep 20

      - name: Checkout main branch into subfolder
        run: |
          git worktree add ../main-worktree main
        shell: bash

      - name: Build and Start main branch on port 4000
        working-directory: ../main-worktree
        env:
          WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
          NEXT_PUBLIC_WORDPRESS_API_URL: "https://wp.keploy.io/graphql"
        run: |
          npm install
          npm run build
          nohup npm run start -- -p 4000 > main.log 2>&1 &
          sleep 20

      - name: Run Lighthouse Comparison
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'http://localhost:3000/blog,http://localhost:4000/blog'
